server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}